name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435
      - uses: actions/setup-node@v3
        with:
          node-version: v22.x
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/node_modules
            ~/.cpcache
          key: deps-${{ hashFiles('deps.edn', 'package.json') }}
          restore-keys: deps-
      - run: yarn
      - run: yarn test